name: Supabase Keep Alive
on:
  schedule:
    - cron: '0 0 */3 * *' # activate every 3 days
  workflow_dispatch:      # allow manual adjustment

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          curl -L -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}"