name: Supabase Keep Alive
on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:      # allow manual adjustment

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping and Verify
        run: |
          RESPONSE=$(curl -f -sS -L -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/characters?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}")

          echo "Server Response: $RESPONSE"

